import { FormEvent, StrictMode, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

type Application = { id: string; company: string; role: string; status: string; dateApplied: string | null; notes: string; url: string; jobDescription: string };
type Analysis = { score:number; matchedKeywords:string[]; missingKeywords:string[]; suggestions:string[]; provider:string };
const blank = { company: "", role: "", status: "Applied", dateApplied: new Date().toISOString().slice(0, 10), jobDescription: "", notes: "", url: "" };
function App() {
  const [applications, setApplications] = useState<Application[]>([]); const [form, setForm] = useState(blank); const [editing, setEditing] = useState<string | null>(null); const [error, setError] = useState(""); const [userId, setUserId] = useState(() => localStorage.getItem("applywise-user-id") || ""); const [credentials, setCredentials] = useState({email:"",password:""}); const [resume,setResume]=useState(""); const [analysis,setAnalysis]=useState<Analysis|null>(null);
  const headers = userId ? { "x-user-id": userId } : {}; const load = () => userId && fetch("/api/applications", {headers}).then(r => r.json()).then(setApplications).catch(() => setError("Could not load applications. Is the API running?"));
  useEffect(load, [userId]);
  useEffect(() => { userId && fetch("/api/resume",{headers}).then(r=>r.ok?r.json():null).then(d=>d&&setResume(d.content)); }, [userId]);
  async function authenticate(event: FormEvent, action: "register" | "login") { event.preventDefault(); const result = await fetch(`/api/auth/${action}`, {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(credentials)}); const data = await result.json(); if (!result.ok) return setError(data.error); localStorage.setItem("applywise-user-id",data.userId); setUserId(data.userId); setError(""); }
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); const endpoint = editing ? `/api/applications/${editing}` : "/api/applications"; const result = await fetch(endpoint, { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json", ...headers }, body: JSON.stringify(form) }); if (!result.ok) return setError("Please complete the required fields and use a valid URL."); setForm(blank); setEditing(null); load(); }
  async function saveResume(event:FormEvent){event.preventDefault();const result=await fetch("/api/resume",{method:"PUT",headers:{"Content-Type":"application/json",...headers},body:JSON.stringify({content:resume})});if(!result.ok)setError("Paste at least 50 characters of resume text.");else setError("");}
  async function analyze(id:string){setError("");const result=await fetch(`/api/applications/${id}/analyze`,{method:"POST",headers});const data=await result.json();if(!result.ok)return setError(data.error);setAnalysis(data);}
  function edit(item: Application) { setEditing(item.id); setForm({ company: item.company, role: item.role, status: item.status, dateApplied: item.dateApplied || "", jobDescription: item.jobDescription, notes: item.notes, url: item.url }); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function remove(id: string) { if (confirm("Delete this application?")) { await fetch(`/api/applications/${id}`, { method: "DELETE" }); load(); } }
  if (!userId) return <main><header><div><p className="eyebrow">JOB SEARCH, ORGANIZED</p><h1>Applywise</h1><p>Create an account to start tracking.</p></div></header><section className="panel auth"><h2>Get started</h2><form onSubmit={e=>authenticate(e,"register")}><input required type="email" placeholder="Email" value={credentials.email} onChange={e=>setCredentials({...credentials,email:e.target.value})}/><input required minLength={8} type="password" placeholder="Password (8+ characters)" value={credentials.password} onChange={e=>setCredentials({...credentials,password:e.target.value})}/><button>Create account</button><button type="button" className="secondary" onClick={e=>authenticate(e as unknown as FormEvent,"login")}>Log in</button></form>{error&&<p className="error">{error}</p>}</section></main>;
  return <main><header><div><p className="eyebrow">JOB SEARCH, ORGANIZED</p><h1>Applywise</h1><p>Track every opportunity in one clear place.</p></div><span>{applications.length} applications</span></header><section className="panel"><h2>Base resume</h2><form onSubmit={saveResume}><textarea required minLength={50} placeholder="Paste your resume text once; it stays private to your account." value={resume} onChange={e=>setResume(e.target.value)}/><button>Save resume</button></form></section><section className="panel"><h2>{editing ? "Edit application" : "Add an application"}</h2><form onSubmit={submit}><input required placeholder="Company *" value={form.company} onChange={e => setForm({...form, company:e.target.value})}/><input required placeholder="Role *" value={form.role} onChange={e => setForm({...form, role:e.target.value})}/><select value={form.status} onChange={e => setForm({...form, status:e.target.value})}>{["Applied","Screening","Interview","Offer","Rejected"].map(s => <option key={s}>{s}</option>)}</select><input type="date" value={form.dateApplied} onChange={e => setForm({...form, dateApplied:e.target.value})}/><input placeholder="Job URL" value={form.url} onChange={e => setForm({...form, url:e.target.value})}/><textarea placeholder="Job description" value={form.jobDescription} onChange={e => setForm({...form, jobDescription:e.target.value})}/><textarea placeholder="Notes" value={form.notes} onChange={e => setForm({...form, notes:e.target.value})}/><button>{editing ? "Save changes" : "Add application"}</button>{editing && <button type="button" className="secondary" onClick={() => {setEditing(null);setForm(blank)}}>Cancel</button>}</form>{error && <p className="error">{error}</p>}</section><section className="panel"><h2>Applications</h2>{applications.length === 0 ? <p className="empty">No applications yet. Add your first role above.</p> : <div className="cards">{applications.map(item => <article key={item.id}><div><strong>{item.company}</strong><span>{item.role}</span></div><span className={`status ${item.status.toLowerCase()}`}>{item.status}</span><small>{item.dateApplied ? `Applied ${item.dateApplied}` : "No date"}</small><div className="actions"><button className="link" onClick={() => analyze(item.id)}>Analyze</button><button className="link" onClick={() => edit(item)}>Edit</button><button className="link danger" onClick={() => remove(item.id)}>Delete</button></div></article>)}</div>}{analysis&&<div className="analysis"><h3>Resume match: {analysis.score}%</h3><p><b>Matched:</b> {analysis.matchedKeywords.join(", ")||"None yet"}</p><p><b>Gaps:</b> {analysis.missingKeywords.join(", ")||"None"}</p><ul>{analysis.suggestions.map(s=><li key={s}>{s}</li>)}</ul><small>Powered by {analysis.provider}</small></div>}</section></main>;
}

createRoot(document.getElementById("root")!).render(<StrictMode><App /></StrictMode>);
