import { randomUUID } from "node:crypto";
import pg from "pg";
import type { CandidateProfile, JobMatch } from "../shared/discovery.js";
const common = new Set(["javascript","typescript","react","node","python","java","sql","aws","docker","figma","excel","salesforce","communication","leadership","agile","git","css","html"]);
const words=(text:string)=>[...new Set((text.toLowerCase().match(/[a-z+#.]{3,}/g)??[]).filter(x=>common.has(x)))];
export const profileFromResume=(text:string):CandidateProfile=>({fullName:text.match(/^([A-Z][a-z]+\s+[A-Z][a-z]+)/m)?.[1]??"",location:text.match(/(?:location|based in)[:\s]+([^\n,]+)/i)?.[1]??"Philippines",targetRoles:(text.match(/(?:software|frontend|backend|full.?stack|data|product|ui\/ux|marketing|sales)\s+(?:engineer|developer|analyst|designer|manager|specialist)/ig)??[]).slice(0,4),skills:words(text),workPreference:/remote/i.test(text)?"remote":"any"});
export interface DiscoveryStore { getProfile(userId:string):Promise<CandidateProfile|undefined>; saveProfile(userId:string,p:CandidateProfile):Promise<void>; saveMatches(userId:string,m:JobMatch[]):Promise<JobMatch[]>; getMatch(userId:string,id:string):Promise<JobMatch|undefined>; listMatches(userId:string):Promise<JobMatch[]> }
export class MemoryDiscoveryStore implements DiscoveryStore { profiles=new Map<string,CandidateProfile>(); matches=new Map<string,JobMatch[]>(); async getProfile(id:string){return this.profiles.get(id)} async saveProfile(id:string,p:CandidateProfile){this.profiles.set(id,p)} async saveMatches(id:string,m:JobMatch[]){const old=this.matches.get(id)??[];const all=[...m,...old.filter(x=>!m.some(y=>y.url===x.url))];this.matches.set(id,all);return all} async getMatch(id:string,mid:string){return (this.matches.get(id)??[]).find(x=>x.id===mid)} async listMatches(id:string){return this.matches.get(id)??[]} }
export class PostgresDiscoveryStore implements DiscoveryStore { constructor(private pool:pg.Pool){} async getProfile(id:string){const r=await this.pool.query("SELECT * FROM candidate_profiles WHERE user_id=$1",[id]);const x=r.rows[0];return x&&{fullName:x.full_name,location:x.location,targetRoles:x.target_roles,skills:x.skills,workPreference:x.work_preference}} async saveProfile(id:string,p:CandidateProfile){await this.pool.query("INSERT INTO candidate_profiles(user_id,full_name,location,target_roles,skills,work_preference) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(user_id) DO UPDATE SET full_name=$2,location=$3,target_roles=$4,skills=$5,work_preference=$6,updated_at=now()",[id,p.fullName,p.location,JSON.stringify(p.targetRoles),JSON.stringify(p.skills),p.workPreference])} async saveMatches(uid:string,m:JobMatch[]){for(const x of m)await this.pool.query("INSERT INTO job_matches(id,user_id,source_url,title,company,location,description,score,match_band,reasons,source) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(user_id,source_url) DO UPDATE SET score=$8,match_band=$9,reasons=$10",[x.id,uid,x.url,x.title,x.company,x.location,x.description,x.score,x.band,JSON.stringify(x.reasons),x.source]);return this.listMatches(uid)} async listMatches(uid:string){const r=await this.pool.query("SELECT * FROM job_matches WHERE user_id=$1 ORDER BY score DESC",[uid]);return r.rows.map(x=>({id:x.id,title:x.title,company:x.company,location:x.location,description:x.description,url:x.source_url,score:x.score,band:x.match_band,reasons:x.reasons,source:x.source}))} async getMatch(uid:string,id:string){return (await this.listMatches(uid)).find(x=>x.id===id)} }
export async function searchJobs(profile:CandidateProfile):Promise<JobMatch[]>{if(!process.env.SERPAPI_API_KEY)throw new Error("Job search is not configured. Add SERPAPI_API_KEY to .env.");const query=profile.targetRoles[0]||profile.skills.slice(0,3).join(" ")||"software developer";const params=new URLSearchParams({engine:"google_jobs",api_key:process.env.SERPAPI_API_KEY,q:query,location:profile.location||"Philippines",gl:"ph",hl:"en"});if(profile.workPreference==="remote")params.set("ltype","1");const r=await fetch(`https://serpapi.com/search.json?${params}`);if(!r.ok){const detail=(await r.text()).replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim().slice(0,180);throw new Error(`Job provider returned ${r.status}${detail?`: ${detail}`:""}`)}const data=await r.json() as {jobs_results?:any[];error?:string};if(data.error)throw new Error(`Job provider error: ${data.error}`);return (data.jobs_results??[]).map(x=>{const text=`${x.title} ${x.description}`.toLowerCase();const hits=profile.skills.filter(s=>text.includes(s));const score=Math.min(100,Math.round(35+(hits.length/Math.max(profile.skills.length,1))*65));const apply=x.apply_options?.[0];return {id:randomUUID(),title:x.title,company:x.company_name??"Unknown company",location:x.location??"Remote",description:x.description??"",url:apply?.link??x.share_link,score,band:score>=70?"Strong match":score>=45?"Possible match":"Low match",reasons:hits.length?[`Matches ${hits.slice(0,4).join(", ")}`]:["Matches your target role"],source:apply?.title??x.via??"Google Jobs"} as JobMatch}).filter(x=>Boolean(x.url))}
