import { randomUUID } from "node:crypto";
import pg from "pg";
import type { CandidateProfile, JobMatch } from "../shared/discovery.js";
const common = new Set(["javascript","typescript","react","node","python","java","sql","aws","docker","figma","excel","salesforce","communication","leadership","agile","git","css","html"]);
const words=(text:string)=>[...new Set((text.toLowerCase().match(/[a-z+#.]{3,}/g)??[]).filter(x=>common.has(x)))];
export const profileFromResume=(text:string):CandidateProfile=>({fullName:text.match(/^([A-Z][a-z]+\s+[A-Z][a-z]+)/m)?.[1]??"",location:text.match(/(?:location|based in)[:\s]+([^\n,]+)/i)?.[1]??"Philippines",targetRoles:(text.match(/(?:software|frontend|backend|full.?stack|data|product|ui\/ux|marketing|sales)\s+(?:engineer|developer|analyst|designer|manager|specialist)/ig)??[]).slice(0,4),skills:words(text),workPreference:/remote/i.test(text)?"remote":"any"});
export interface DiscoveryStore { getProfile(userId:string):Promise<CandidateProfile|undefined>; saveProfile(userId:string,p:CandidateProfile):Promise<void>; saveMatches(userId:string,m:JobMatch[]):Promise<JobMatch[]>; getMatch(userId:string,id:string):Promise<JobMatch|undefined>; listMatches(userId:string):Promise<JobMatch[]> }
export class MemoryDiscoveryStore implements DiscoveryStore { profiles=new Map<string,CandidateProfile>(); matches=new Map<string,JobMatch[]>(); async getProfile(id:string){return this.profiles.get(id)} async saveProfile(id:string,p:CandidateProfile){this.profiles.set(id,p)} async saveMatches(id:string,m:JobMatch[]){const old=this.matches.get(id)??[];const all=[...m,...old.filter(x=>!m.some(y=>y.url===x.url))];this.matches.set(id,all);return all} async getMatch(id:string,mid:string){return (this.matches.get(id)??[]).find(x=>x.id===mid)} async listMatches(id:string){return this.matches.get(id)??[]} }
export class PostgresDiscoveryStore implements DiscoveryStore { constructor(private pool:pg.Pool){} async getProfile(id:string){const r=await this.pool.query("SELECT * FROM candidate_profiles WHERE user_id=$1",[id]);const x=r.rows[0];return x&&{fullName:x.full_name,location:x.location,targetRoles:x.target_roles,skills:x.skills,workPreference:x.work_preference}} async saveProfile(id:string,p:CandidateProfile){await this.pool.query("INSERT INTO candidate_profiles(user_id,full_name,location,target_roles,skills,work_preference) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(user_id) DO UPDATE SET full_name=$2,location=$3,target_roles=$4,skills=$5,work_preference=$6,updated_at=now()",[id,p.fullName,p.location,p.targetRoles,p.skills,p.workPreference])} async saveMatches(uid:string,m:JobMatch[]){for(const x of m)await this.pool.query("INSERT INTO job_matches(id,user_id,source_url,title,company,location,description,score,match_band,reasons,source) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(user_id,source_url) DO UPDATE SET score=$8,match_band=$9,reasons=$10",[x.id,uid,x.url,x.title,x.company,x.location,x.description,x.score,x.band,x.reasons,x.source]);return this.listMatches(uid)} async listMatches(uid:string){const r=await this.pool.query("SELECT * FROM job_matches WHERE user_id=$1 ORDER BY score DESC",[uid]);return r.rows.map(x=>({id:x.id,title:x.title,company:x.company,location:x.location,description:x.description,url:x.source_url,score:x.score,band:x.match_band,reasons:x.reasons,source:x.source}))} async getMatch(uid:string,id:string){return (await this.listMatches(uid)).find(x=>x.id===id)} }
export async function searchJobs(profile:CandidateProfile):Promise<JobMatch[]>{if(!process.env.ADZUNA_APP_ID||!process.env.ADZUNA_APP_KEY)throw new Error("Job search is not configured. Add ADZUNA_APP_ID and ADZUNA_APP_KEY to .env.");const query=encodeURIComponent(profile.targetRoles[0]||profile.skills.slice(0,3).join(" ")||"software developer");const r=await fetch(`https://api.adzuna.com/v1/api/jobs/ph/search/1?app_id=${process.env.ADZUNA_APP_ID}&app_key=${process.env.ADZUNA_APP_KEY}&what=${query}&results_per_page=20&content-type=application/json`);if(!r.ok)throw new Error("Job provider search failed.");const data=await r.json() as {results?:any[]};return (data.results??[]).map(x=>{const text=`${x.title} ${x.description}`.toLowerCase();const hits=profile.skills.filter(s=>text.includes(s));const score=Math.min(100,Math.round(35+(hits.length/Math.max(profile.skills.length,1))*65));return {id:randomUUID(),title:x.title,company:x.company?.display_name??"Unknown company",location:x.location?.display_name??"Remote",description:x.description??"",url:x.redirect_url,score,band:score>=70?"Strong match":score>=45?"Possible match":"Low match",reasons:hits.length?[`Matches ${hits.slice(0,4).join(", ")}`]:["Matches your target role"],source:"Jobs by Adzuna"} as JobMatch})}
